microdotblog/microblog-react

ios/Podfile.lock, package.json, src/screens/posts/image_crop.js, src/stores/App.js, yarn.lock
Added a few basic filters to crop photo interface.
=> Photo filters

src/screens/posts/image_crop.js
More filters: Warm, Cool, and Vintage. Renamed Normal to Original. Also fixed the layout of the bottom part of the filters screen.
=> Final photo filter changes

ios/MicroBlog_RN.xcodeproj/project.pbxproj, ios/MicroBlog_RN/Images.xcassets/color_editing_paragraph.colorset/Contents.json, ios/MicroBlog_RN/Images.xcassets/color_syntax_tags.colorset/Contents.json, ios/MicroBlog_RN/MBHighlightingTextManager.h, ios/MicroBlog_RN/MBHighlightingTextManager.m, ios/MicroBlog_RN/MBHighlightingTextStorage.h, ios/MicroBlog_RN/MBHighlightingTextStorage.m, ios/MicroBlog_RN/MBHighlightingTextView.h, ios/MicroBlog_RN/MBHighlightingTextView.m, src/components/text/highlighting_text.js, src/screens/posts/new.js
There's still more to tweak but I think this is ready for a beta. Some notes:
* Currently only used for new posts.
* Text size insertion cursor is wrong before typing.
* Ignores many of the React properties right now.
* Won't work on Android. Need to conditionally use `TextInput` instead.
=> Markdown syntax highlighting

src/components/keyboard/reply_toolbar.js, src/stores/models/Posting.js
Adjust position higher when usernames are visible.
=> Fixed usernames bar

ios/MicroBlog_RN.xcodeproj/project.pbxproj, ios/MicroBlog_RN/MBHighlightingTextManager.m, ios/MicroBlog_RN/MBHighlightingTextView.m, src/components/share/header.js, src/screens/posts/new.js, src/screens/share/index.js, src/screens/share/post.js, src/stores/Share.js
This should be the 3.0.3 release. Submitting to Apple now.
=> Share sheet tweaks

android/app/build.gradle, ios/MicroBlog_RN.xcodeproj/project.pbxproj, src/api/MicroBlogApi.js, src/api/MicroPubApi.js, src/components/cells/upload_cell.js, src/components/generic/generic_screen.js, src/screens/bookmarks/bookmarks.js, src/screens/conversation/conversation.js, src/screens/discover/discover.js, src/screens/discover/topic.js, src/screens/following/following.js, src/screens/index.js, src/screens/mentions/mentions.js, src/screens/posts/image_options.js, src/screens/posts/new.js, src/screens/settings/post_options.js, src/stores/App.js, src/stores/Reply.js, src/stores/Services.js, src/stores/models/Posting.js, src/stores/models/User.js
Merging in bug fixes that will probably be the 3.0.4 release.
=> 3.0.4 bug fixes

ios/MicroBlog_RN/MBHighlightingTextManager.h, ios/MicroBlog_RN/MBHighlightingTextManager.m, ios/MicroBlog_RN/MBHighlightingTextStorage.m
Merging in last changes from branch for 3.0.4.
=> Post editor font size

src/api/MicroPubApi.js, src/stores/models/posting/MediaAsset.js, src/stores/models/posting/TempUpload.js
=> Use response.header.location for setting Media upload url.

android/app/build.gradle, src/components/header/profile_image.js
=> Android 1.9 release

src/api/XMLRPCApi.js
=> Fixed WordPress categories

src/components/cells/upload_cell.js, src/components/keyboard/asset_toolbar.js, src/components/keyboard/post_toolbar.js, src/screens/index.js, src/screens/posts/new.js, src/screens/posts/options.js, src/screens/uploads/uploads.js, src/stores/models/Posting.js, src/stores/models/posting/MediaAsset.js, src/stores/models/posting/Upload.js
Added audio icon, other changes.
=> Post editor, toolbar changes

README.md, src/components/push/push_notifications.js, src/components/sheets/notifications.js, src/components/web/webview_module.js, src/screens/index.js, src/stores/Push.js, src/stores/models/Notification.js
=> Better notifications

src/screens/help/help.js
Also made team profile icons smaller.
=> Added book link

src/screens/posts/image_options.js, src/stores/models/posting/Config.js, src/stores/models/posting/Service.js
=> Alt text keyboard and destination

src/components/keyboard/post_toolbar.js, src/screens/posts/new.js, src/stores/models/User.js
Merging this in, should be the final 3.2.1 change.
=> Hide audio upload if not Premium

ios/Podfile.lock, src/components/cells/upload_cell.js
@vincentritter Moved this upload cell rendering around to make it easier to just insert directly when tapped. Lemme know if you have any problems with this.
=> Insert link from uploads cell

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, src/stores/Push.js
=> Latest Android changes

ios/MicroBlog_RN.xcodeproj/project.pbxproj, ios/MicroBlog_RN/AppDelegate.m, ios/MicroBlog_RN/MBHighlightingTextManager.m, ios/MicroBlog_RN/MBHighlightingTextView.m, ios/MicroBlog_RN/RCTInputAccessoryShadowView.h, ios/MicroBlog_RN/RCTInputAccessoryShadowView.m, src/components/keyboard/reply_toolbar.js, src/components/sheets/menu.js, src/screens/conversation/reply.js, src/screens/index.js, src/screens/pages/edit.js, src/screens/posts/edit.js, src/screens/posts/new.js, src/screens/replies/edit.js, src/screens/replies/replies.js, src/screens/share/post.js, src/stores/models/Posting.js, src/stores/models/posting/Page.js, src/stores/models/posting/Post.js
Mostly around adding the native Markdown highlighting view.
=> Various iOS editor tweaks

ios/MicroBlog_RN.xcodeproj/project.pbxproj, src/api/MicroBlogApi.js, src/components/cells/upload_cell.js, src/components/discover/tagmoji_bar.js, src/components/sheets/upload_info.js, src/screens/index.js, src/screens/pages/edit.js, src/screens/pages/pages.js, src/screens/posts/edit.js, src/screens/posts/posts.js, src/screens/replies/replies.js, src/screens/uploads/uploads.js, src/stores/App.js, src/stores/models/posting/Destination.js, src/stores/models/posting/Service.js, src/stores/models/posting/Upload.js
Added a Get Info option to the context menu for uploads. Shows the URL and any auto-generated accessibility text, with a copy button. We can add more info here in the future.
=> Added uploads Get Info sheet

android/app/build.gradle, src/components/cells/page_cell.js, src/components/cells/post_cell.js, src/screens/pages/pages.js, src/screens/posts/posts.js, src/stores/App.js
Fixes and version update for version 2.2.
=> 2.2 for Android

ios/MicroBlog_RN/MBHighlightingTextManager.m, ios/MicroBlog_RN/MBHighlightingTextView.h, ios/MicroBlog_RN/MBHighlightingTextView.m, src/stores/App.js
Lots of hacks. This is mostly temporary until we replace the text editor with the HTML/JS version, which will be cross-platform and play more nicely with React Native.
=> Editor scrolling fixes

.gitignore, android/app/build.gradle, src/api/MicroBlogApi.js, src/components/generic/publishing_progress.js, src/components/keyboard/reply_toolbar.js, src/components/sheets/reply_sheet.js, src/screens/App.js, src/stores/App.js, src/stores/Reply.js, src/stores/models/Posting.js
Hey @manton,
This change adds the publishing status message at the bottom of the screen, similar to what we have on the web version. It'll slide in, check progress, and update accordingly. You can close it at any time without issue. Additionally it will show you a "View" link when it's done with publishing allowing you to view your post on your blog.
https://github.com/user-attachments/assets/8deea246-b30a-460e-bf51-9457eafee981
I've also added the tweaks to the reply toolbar as mentioned here. I've made a subtle change to the background colour in dark mode, so hopefully that will contrast better. The toolbar will also now organise selected @-mentions according to the way they show up in the text — we could change this to bring back the old behaviour if it's too confusing.
=> Add publishing status. Tweak Reply modal.

src/stores/App.js
Hey @manton,
This fixes an issue that would incorrectly handle usernames that also contained an instance name (i.e. mastodon).
Before it would treat "[@]name[@]instance" as two different usernames and would take the second parameter and would instead search for "[@]instance" instead of the full username.
Please ignore the formatting changes to the file and have a look at the `check_username` function: [`fix/double-at-reply-fix?expand=1`#diff-2f921c0f64](https://github.com/microdotblog/microblog-react/compare/fix/double-at-reply-fix?expand=1#diff-2f921c0f64464407e3dc1940079373770788a45dd294912abda6a958e5a2aeb2R667).
Two changes here are the regex and also not returning no found users if we din't hit the search criteria — this is on purpose so that the username panel doesn't close as we …
=> Fix double "@" when checking usernames.
